### ISSUE TITLE
pip install throwing exception

### ISSUE THREAD

**Issue by 1ab1** [ustream/openduty#81]
pip install -r requirements.txt
`
Exception:
Traceback (most recent call last):
  File "/root/virtualenvs/openduty/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/root/virtualenvs/openduty/local/lib/python2.7/site-packages/pip/commands/install.py", line 262, in run
    for req in parse_requirements(filename, finder=finder, options=options, session=session):
  File "/root/virtualenvs/openduty/local/lib/python2.7/site-packages/pip/req.py", line 1631, in parse_requirements
    req = InstallRequirement.from_line(line, comes_from, prereleases=getattr(options, "pre", None))
  File "/root/virtualenvs/openduty/local/lib/python2.7/site-packages/pip/req.py", line 172, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/root/virtualenvs/openduty/local/lib/python2.7/site-packages/pip/req.py", line 70, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/root/virtualenvs/openduty/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2606, in parse
    reqs = list(parse_requirements(s))
  File "/root/virtualenvs/openduty/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2544, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/root/virtualenvs/openduty/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2512, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'kombu~=3.0', 'at', '~=3.0')
`

**Comment by hanynowsky** [comment]
Got the same issue here in Debian 8. Something wrong with KOMBI

**Comment by hanynowsky** [comment]
Maybe changing komb~=3.0 to kombu==3.0 in requirements.txt fixes it.
but again you get another error later related to OpenLDAP = fatal error: lber.h: No such file or directory
