### ISSUE TITLE
Multiprocessing problems

### ISSUE THREAD

**Issue by kjetilmjos** [ustream/openduty#90]
Hi I'm experiencing problems with the `.apply_asynch` method in the `helper.py` line 20. 
If I leave the `.apply_asynch` on no notifications are sent. Have tried to remove asynch by replacing the line:
`send_notifications.apply_async((notification.id,) ,eta=notification.send_at)`
with
`send_notifications(notification.id)`
This works and I'm then able to send notifications. 

Problem is then off-course that only the first configured notification is sent due to the code being synchronous. Has anybody encountered the same issues?

Really like the functionality of Openduty and to have a open source and free alternative to the expensive pagerduty etc. Would be really nice if we could get a more active community up and running around the repo and maybe port the code to python 3?

**Comment by hanynowsky** [comment]
The Twilio Notification works fine for me. I receive SMS. Well at least the first time. 
The email notification has an issue. It does not work. The task is executed but after 254 seconds, reports an error.  I am going to check shortly again what error it reports.

**Comment by hanynowsky** [comment]
Well. Sounds there is a strange problem.
`[2017-09-21 09:41:59,617: INFO/MainProcess] Received task: notification.tasks.send_notifications[d7e0b16d-f6f7-4ab1-9849-651249ea7463] eta:[2017-09-21 09:41:55.707664+00:00]
[2017-09-21 09:41:59,630: INFO/MainProcess] Received task: notification.tasks.send_notifications[767dd7cc-6da7-415f-b1a4-75f904772ae4] eta:[2017-09-21 09:42:55.707664+00:00]
[2017-09-21 09:41:59,646: INFO/MainProcess] Received task: notification.tasks.send_notifications[82f101d7-614b-4091-a0cc-30686ce50871] eta:[2017-09-21 09:43:55.707664+00:00]




































[2017-09-21 09:42:55,736: WARNING/ForkPoolWorker-6] Failed to send Rocket message:Invalid URL u'': No schema supplied. Perhaps you meant http://?
[2017-09-21 09:42:55,748: ERROR/MainProcess] Task notification.tasks.send_notifications[767dd7cc-6da7-415f-b1a4-75f904772ae4] raised unexpected: MissingSchema("Invalid URL u'': No schema supplied. Perhaps you meant http://?",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/openduty/notification/tasks.py", line 39, in send_notifications
    notifier.notify(notification)
  File "/opt/openduty/notification/notifier/rocket.py", line 11, in notify
    response = requests.post(notification.user_to_notify.profile.rocket_webhook_url, payload)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 94, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 443, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 374, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 304, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 358, in prepare_url
    "Perhaps you meant http://{0}?".format(url))
MissingSchema: Invalid URL u'': No schema supplied. Perhaps you meant http://?

[2017-09-21 09:43:56,740: INFO/MainProcess] Task notification.tasks.send_notifications[82f101d7-614b-4091-a0cc-30686ce50871] succeeded in 1.02826371184s: None

`

**Comment by hanynowsky** [comment]
Well notifications seem not working for me when an incident is triggered. They only work when I click on the TEST NOTIFICATIONS in the user page. :(
The error I have now is related to ROCKET  config. I don't know how it should be, since there is no doc for it.
Well for now I did not modify any code yet!

**Comment by hanynowsky** [comment]
Ok. I confirm that notifications for Twilio SMS are working when an event is triggered.
[2017-09-21 10:01:05,581: INFO/MainProcess] Task notification.tasks.send_notifications[64576a82-1608-400b-a985-dd254449c99a] succeeded in 0.981761767995s: None

**Comment by hanynowsky** [comment]
I am running on a Debian 8

**Comment by hanynowsky** [comment]
Fixed for ROCKET first error. Rocket Webhook URl must be set in USer's profile not in settings.py

**Comment by kjetilmjos** [comment]
Found the "Solution" pretty embarrassing... Turns out celery has to be started seperately. Probably therefore 'celery -A openduty worker -l info' is listed in the Readme file...

**Comment by hanynowsky** [comment]
@kjetilmjos co gratulations. 
I thought that was obvious to you. The readme file must be rewritten.

Anyway, have you succeeded in running celery using supervisord as a daemonizer?
I am running openduty django app using supervisor and it s fine, but no way with celery.
FYI, i am not using virtualenv, since debian jessie comes with python 2.7 natively.

**Comment by kjetilmjos** [comment]
Is that the same as running it in daemon mode using systemd? I found a fork from Oxalide, they have made the pull request here with a range of improvements posted by @sofixa. In their repo there is also a folder showing how the project can be runned as deamon using systemd. Check out the systemd folder at: https://github.com/Oxalide/openduty

**Comment by hanynowsky** [comment]
Perfect. That is better. Thanks a lot.
For the email, i guess there is another way to use yours by adding a custom notifier.
The default one if for gmail.

**Comment by kjetilmjos** [comment]
The one I use works with the oxalide fork. They have written a more general email notifier than the original email based one.

**Comment by hanynowsky** [comment]
Great. Thanks
